global using MinimalApiWindowsService.Constants;
global using MinimalApiWindowsService.Extensions;
global using MinimalApiWindowsService.Extensions.Helpers;
global using MinimalApiWindowsService.Models;
global using MinimalApiWindowsService.Services;